library(dplyr)
df<-globaldata
df1<-select(df,iyear,region_txt)
df2<-summarise(group_by(df1,iyear,region_txt),count=n())
df2<-globaldata %>% count(iyear,region_txt)
df2$iyear<-df2$iyear-(df2$iyear%%10)
df2<-summarize(group_by(df2,iyear,region_txt),attacks=sum(n,na.rm=TRUE))
df3<-summarize(group_by(df2,iyear),Sum=sum(attacks,na.rm=TRUE))
colnames(df3)<-c("decade","totalAttacks")
library(tidyr)
df2<-merge(df3,df2,by.x="decade",by.y="iyear")
df2$propOvrDecades<-round(df2$attacks/df2$totalAttacks,3)

df2<-df2 %>% select(decade,region_txt,propOvrDecades)
write.csv(df2,'proportions.csv')

MENA<-globaldata  %>% filter(region_txt=="Middle East & North Africa")
SA<-globaldata  %>% filter(region_txt=="South Asia")
MENA$decade<-MENA$iyear-(MENA$iyear%%10)
SA$decade<-SA$iyear-(SA$iyear%%10)
MENA_CT<-MENA %>% filter(gname != "Unknown") %>% select(country_txt,gname) 
MENA_CT<-summarise(group_by(MENA_CT,country_txt,gname),count=n())
SA_CT<-SA %>% filter(gname!="Unknown") %>% select(country_txt,gname)
SA_CT<-summarise(group_by(SA_CT,country_txt,gname),count=n())
write.csv(MENA_CT,'MENA1.csv') 
write.csv(SA_CT,'SA1.csv') 
MENA_CP<-select(MENA_CT,country_txt) 
MENA_CP<-summarise(group_by(MENA_CT,country_txt),count=n())
write.csv(MENA_CP,'MENA.csv')
#hyptest<-select(hyptest,weaptype1_txt)
#hyptest<-summarise(group_by(hyptest,weaptype1_txt),count=n())
write.csv(hyptest,'hypothesis.csv')
library(ggplot2)
ggplot(hyptest,aes(x=weaptype1_txt,y=count,fill=weaptype1_txt))+geom_bar(position="dodge",stat="identity")
temp<-select(df,iyear,weapsubtype1_txt)
temp$iyear<-temp$iyear-(temp$iyear%%10)
write.csv(temp,'test.csv')
hyp<-summarise(group_by(datasetw,ï..year,wepon.type),count=n())
write.csv(hyp,'hyp.csv')

